### ISSUE TITLE
./vendor/phpunit/phpunit/phpunit not recognized as php on Windows

### ISSUE THREAD

**Issue by happy-sadan** [elonmallin/vscode-phpunit#32] opened 2019-04-04 21:37 UTC
**Operating system:** Windows 10
**PHPUnit version:** 8.0.6

Whenever I run a test, I receive the following response from the terminal:
```
> Executing task:  c:/path/to/project/vendor/phpunit/phpunit/phpunit c:/path/to/project/tests/Unit/UnitTest.php --filter testExample <

'c:/path/to/project/vendor/phpunit/phpunit/phpunit' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
Running the _Executing task_ command prepended with `php` works, the terminal doesn't seem to recognize the file as being **PHP**.

**Comment by elonmallin** [comment] 2019-04-05 05:12
Yes, that's true. Windows doesn't understand that it's a php file. On windows you have to set the config phpunit.php to be the php executable or set it in your environment variables in the path so it's available globally from command line.

What is your config?

You should actually need no config if you have php on command line and phpunit in vendor dir.

**Comment by happy-sadan** [comment] 2019-04-07 22:08
I saw that, but I do have both php globally installed and phpunit in my `vendor` directory.

I tried this in a fresh project, just installing **PHPUnit** and creating a test file. If I run `vendor\bin\phpunit`, it works, **but** if i run `vendor/bin/phpunit` (with _forward slashes_), I get the same error.

As I said, just prepending `php` to the same command makes it work (even with _forward slashes_). But without it, Windows doesn't recognize the file as an executable.

**Comment by elonmallin** [comment] 2019-05-01 14:29
Hmm, it works on my Windows machine. I have no config and php in the environment path and phpunit in the vendor dir. The output you pasted looks like it has two spaces in the beginning so I think there is something wrong somewhere. Maybe you have `phpunit.php: " "` or something equivalent set somewhere?

I get this output in the tasks pane:
```
Executing task: php c:/Projects/myproject/vendor/phpunit/phpunit/phpunit 'c:/Projects/myproject/tests/AppBundle/StandaloneTest.php' --filter testStandalone <
```
Since your output is missing the `php` in the beginning it wasn't found globally. Could you please test 
 `php --version` in a command prompt to make sure it's installed correctly?

And this output in the ouput pane:
```
Running phpunit with driver: Composer
php c:/Projects/myproject/vendor/phpunit/phpunit/phpunit 'c:/Projects/myproject/tests/AppBundle/StandaloneTest.php' --filter testStandalone
```

Sorry for getting back so late but hope that helps or that you already figured it out. Closing this since I believe it to be a config problem. Please do get back to me it if't still not working =)

**Closed by elonmallin** 2019-05-01 14:29 UTC

**Comment by happy-sadan** [comment] 2019-05-01 20:20
PHP is indeed installed correctly. I tried setting `phpunit.php` to `php`, which made it work when running the entire test suite. I then tried removing it, and it still worked. It seems like `phpunit.php` was originally using the empty string it contained instead of finding PHP globally. This was thus fixed by setting `phpunit.php` to `php` (or probably any value), then setting it back to an empty string.

But I have one last problem. When running PHPUnit on any specific file, I get this error :

```
> Executing task: php c:/path/to/project/vendor/phpunit/phpunit/phpunit 'c:/path/to/project/tests/ExampleTest.php' <

Cannot open file "'c:/path/to/project/tests/ExampleTest'.php".

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

This command only seems to work with double quotes instead of single quotes, like this:

```
php c:/path/to/project/vendor/phpunit/phpunit/phpunit "c:/path/to/project/tests/ExampleTest.php"
```

**Comment by elonmallin** [comment] 2019-05-02 09:48
Okey, nice that the original issue seems to be working now.

First I couldn't reproduce your second bug but it seems that it only happens if your default shell in VSCode is set to `cmd.exe` instead of `powershell.exe`. Which it can be if you are on an earlier version of windows than Windows 10 or if you've set it manually to be `cmd.exe` in your settings in VSCode.

I can have a look at fixing that since `"` works for any scenario so it's better to use that.

In the meantime you could try and set your shell to be `powershell.exe` by setting it in your settings: https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
Hopefully this will run the extension in powershell instead so it works.

**Comment by happy-sadan** [comment] 2019-05-13 22:21
That was indeed the problem, all good now !

**Comment by happy-sadan** [comment] 2019-05-13 23:07
Any idea when the next version will be released ?

**Comment by elonmallin** [comment] 2019-05-14 05:33
Nice :) I don't have so many things in the pipe so not sure. Maybe I'll have a look at it this weekend.
